Add support for StringIndexoutofbounds Exception in charAt and SubString

diff --git a/jpf-sv-comp b/jpf-sv-comp
--- a/jpf-sv-comp
+++ b/jpf-sv-comp
@@ -68,7 +68,7 @@ echo "symbolic.lazy=on" >> $DIR/config.jpf
 echo "symbolic.arrays=true" >> $DIR/config.jpf
 if [ $RUNTIME_EXCEPTION_MODE = "TRUE" ] ; then
   echo "runtime.exception=true" >> $DIR/config.jpf
-  #echo "search.multiple_errors = true" >> $DIR/config.jpf
+  echo "search.multiple_errors=true" >> $DIR/config.jpf
 fi
 echo $DIR/config.jpf
 
@@ -111,11 +111,16 @@ elif [ $RUNTIME_EXCEPTION_MODE = "TRUE" ]; then
   grep "java.lang.*Exception" $LOG > /dev/null
   JAVA_EXCEPTION=$?
 
+  grep "java.lang.ClassNotFoundException" $LOG > /dev/null
+  CLASS_NOT_FOUND=$?
+
   grep "no errors detected" $LOG > /dev/null
   NO_ERRORS=$?
 
   if ([ $ASSERTION_ERROR -eq 0 ] && [ $JAVA_EXCEPTION -ne 0 ]) || [ $NO_ERRORS -eq 0 ]; then
     echo "SAFE"
+  elif [ $CLASS_NOT_FOUND -eq 0 ]; then
+    echo "UNKNOWN"
   elif [ $JAVA_EXCEPTION -eq 0 ]; then
     echo "UNSAFE"
   else
